[uwsgi]
# Django-related settings
chdir           = /home/ubuntu/bin/server/
module          = backend.wsgi
home            = /home/ubuntu/venv/

# process-related settings
master          = true
processes       = 2

# the socket (use the full path to be safe)
#http 		= :8000
#socket		= :8000
socket          = /home/ubuntu/bin/nginx_to_django.sock

chmod-socket    = 711
vacuum          = true
