# Generated by Django 4.2.4 on 2023-11-24 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='result/image/')),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('setup_data', models.FileField(upload_to='setup/json/')),
                ('public', models.BooleanField(default=False)),
                ('work_request', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='setup/image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='process/image/')),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qutat.setup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='result/json/')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qutat.output')),
            ],
        ),
        migrations.AddField(
            model_name='output',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qutat.setup'),
        ),
        migrations.AddField(
            model_name='output',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='etc/image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
