# Generated by Django 4.2.4 on 2023-12-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qutat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='input',
            field=models.FileField(blank=True, null=True, upload_to='result/json/'),
        ),
    ]
