# Generated by Django 4.2.4 on 2024-02-13 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qutat', '0002_output_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='input/json/')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qutat.setup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
