# Generated by Django 4.2.4 on 2024-02-14 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qutat', '0004_input_description_input_public_input_results_exist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output2',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='result/image/')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qutat.input')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
