# Generated by Django 4.2.4 on 2024-02-14 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qutat', '0005_output2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output2File',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='result/json/')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qutat.output2')),
            ],
        ),
    ]
