# Generated by Django 4.2.4 on 2024-02-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qutat', '0006_output2file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputfile',
            name='output',
        ),
        migrations.RemoveField(
            model_name='process',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='process',
            name='user',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.DeleteModel(
            name='OutputFile',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
