# Generated by Django 4.2.4 on 2024-02-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qutat', '0007_remove_outputfile_output_remove_process_setup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='process_exist',
            field=models.BooleanField(default=False),
        ),
    ]
