# Generated by Django 4.2.4 on 2024-09-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qutat', '0009_alter_input_results_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='solver',
            field=models.TextField(default='FDTD:PEEM'),
            preserve_default=False,
        ),
    ]
