class RestApi():
    def public_setup_list():return "/qutat/public/setup/list/"
    def public_process_search_by_setup(setup_id: str):return "/qutat/public/process2/search/setup/"+setup_id+"/"
    def setup_data(setup_id: str):return "/qutat/setup/data/"+setup_id+"/"
    def input_generate(setup_id: str, num_input: str):return "/qutat/input/generate/"+setup_id+"/"+num_input+"/"
    def model_setup(variable: str):return "/qutat/model/setup/"+variable+"/"
    def model_input(variable: str):return "/qutat/model/input/"+variable+"/"
    def results(setup_id: str):return "/qutat/results/"+setup_id+"/"
    def results_wo_output(setup_id: str):return "/qutat/results_wo_output/"+setup_id+"/"
    #def setup_tasks(setup_id: str):return "/qutat/setup/tasks/"+setup_id+"/"
    def output2_files(input_id: str):return "/qutat/output2/files/"+input_id+"/"
    def results_files(input_id: str):return "/qutat/results/files/"+input_id+"/"
    def entity_data(input_id: str):return "/qutat/entity/data/"+input_id+"/"
    def process_request_task2():return "/qutat/process/request-task2/"
    def model_process2(variable: str):return "/qutat/model/process2/"+variable+"/"
    def process2_return(process_id: str):return "/qutat/process2/return/"+process_id+"/"
    #def image_upload():return "/qutat/image/upload/"
    #def registration():return "/users/registration/"
    #def token_new():return "/users/token/new/"
    #def token_view(variable: str):return "/users/token/view/"+variable+"/"
    #def token_check():return "/users/token/check/"
    def users_login():return "/users/login/"
    def users_logout():return "/users/logout/"
    def users_user():return "/users/user/"