// Generated by scripts/generate-cad-api.mjs from manifest.json. Do not edit.
import { boxManifest } from './primitives/box/definition'
import { cylinderManifest } from './primitives/cylinder/definition'
import { curvedEdgeCylinderManifest } from './primitives/curvedEdgeCylinder/definition'
import { sphereManifest } from './primitives/sphere/definition'
import { curvedSurfaceSphereManifest } from './primitives/curvedSurfaceSphere/definition'
import { fiberManifest } from './primitives/fiber/definition'
import { shellManifest } from './operations/shell/definition'
import { arrayManifest } from './operations/array/definition'
import { unionManifest, subtractManifest, intersectManifest } from './operations/booleans/definition'
import { boxDefinition } from './primitives/box/runtime'
import { cylinderDefinition } from './primitives/cylinder/runtime'
import { curvedEdgeCylinderDefinition } from './primitives/curvedEdgeCylinder/runtime'
import { sphereDefinition } from './primitives/sphere/runtime'
import { curvedSurfaceSphereDefinition } from './primitives/curvedSurfaceSphere/runtime'
import { fiberDefinition } from './primitives/fiber/runtime'
import { shellDefinition } from './operations/shell/runtime'
import { arrayDefinition } from './operations/array/runtime'
import { unionDefinition, subtractDefinition, intersectDefinition } from './operations/booleans/runtime'
import type { CadElementDefinition } from '../evaluation/types'

export const cadElementCatalog = [
  boxManifest,
  cylinderManifest,
  curvedEdgeCylinderManifest,
  sphereManifest,
  curvedSurfaceSphereManifest,
  fiberManifest,
  shellManifest,
  arrayManifest,
  unionManifest,
  subtractManifest,
  intersectManifest,
] as const

export const cadElementDefinitions = [
  boxDefinition,
  cylinderDefinition,
  curvedEdgeCylinderDefinition,
  sphereDefinition,
  curvedSurfaceSphereDefinition,
  fiberDefinition,
  shellDefinition,
  arrayDefinition,
  unionDefinition,
  subtractDefinition,
  intersectDefinition,
] as const satisfies readonly CadElementDefinition[]
