// Generated by scripts/generate-cad-api.mjs from elements/manifest.json. Do not edit.
import type {
  ArrayAttributes,
  BooleanAttributes,
  BoxAttributes,
  CurvedEdgeCylinderAttributes,
  CurvedSurfaceSphereAttributes,
  CylinderAttributes,
  FiberAttributes,
  ShellAttributes,
  SphereAttributes,
} from '@caemble/core'

declare global {
  function h(type: unknown, attributes: unknown, ...children: unknown[]): unknown
  function Fragment(props: { children?: unknown }): unknown

  namespace JSX {
    interface IntrinsicElements {
      box: BoxAttributes
      cylinder: CylinderAttributes
      curvedEdgeCylinder: CurvedEdgeCylinderAttributes
      sphere: SphereAttributes
      curvedSurfaceSphere: CurvedSurfaceSphereAttributes
      fiber: FiberAttributes
      shell: ShellAttributes
      array: ArrayAttributes
      union: BooleanAttributes
      subtract: BooleanAttributes
      intersect: BooleanAttributes
    }
  }
}

export {}
