// Generated by scripts/generate-cad-api.mjs from the production kernel descriptors. Do not edit.
// @caemble/kernels declaration version: 0.0.0
import type {
  CartesianBasis,
  DataAxis,
  DefinedKernelTask,
  FloatDataDType,
  MaterialDataValueDescriptor,
  QuantityKindName,
  NonFloatDataDType,
  ScalarQuantityKindName,
  UcumUnit,
} from '@caemble/core'

type FloatParameter<DType extends FloatDataDType, QuantityKind extends QuantityKindName> = Readonly<{
  dtype: DType
  value: number | readonly unknown[]
  unit: UcumUnit
  quantityKind: QuantityKind
  axes?: readonly DataAxis[]
}> &
  (QuantityKind extends ScalarQuantityKindName ? Readonly<{ basis?: never }> : Readonly<{ basis?: CartesianBasis }>)

type NonFloatParameter<
  DType extends NonFloatDataDType,
  Value extends boolean | string | number | readonly unknown[],
> = Readonly<{
  dtype: DType
  value: Value
  axes?: readonly DataAxis[]
  unit?: never
  quantityKind?: never
  basis?: never
}>

export type DcCurrentDensityInitialization = Readonly<{
  methodId: 'dc.voxel-grid'
  target: readonly `structure.geometry.${string}`[]
  parameters: Readonly<{
    gridShape: NonFloatParameter<'int32', readonly [number, number, number]>
  }>
}>

export type DcCurrentDensityBoundaryCondition =
  | Readonly<{
      methodId: 'dc.source-potential'
      target: readonly `structure.surface.${string}`[]
      parameters: Readonly<{
        voltage: FloatParameter<'float64', 'electromagnetism.Voltage'>
      }>
    }>
  | Readonly<{
      methodId: 'dc.reference-potential'
      target: readonly `structure.surface.${string}`[]
      parameters: Readonly<{
        voltage: FloatParameter<'float64', 'electromagnetism.Voltage'>
      }>
    }>

export type DcCurrentDensityOutput =
  | Readonly<{
      key: string
      methodId: 'dc.current-density'
      target: readonly `structure.geometry.${string}`[]
      parameters: Readonly<{
        crossSectionPosition: FloatParameter<'float64', 'DimensionlessRatio'>
      }>
    }>
  | Readonly<{
      key: string
      methodId: 'dc.total-current'
      target: readonly `structure.geometry.${string}`[]
      parameters: Readonly<{
        crossSectionPosition: FloatParameter<'float64', 'DimensionlessRatio'>
      }>
    }>
  | Readonly<{
      key: string
      methodId: 'dc.joule-heating'
      target: readonly `structure.geometry.${string}`[]
      parameters: Readonly<Record<string, never>>
    }>

export type DcCurrentDensityConductorMaterialVariables = Readonly<{
  'electrical.conductivity': MaterialDataValueDescriptor<'electrical.conductivity'>
}>

export type DcCurrentDensityTaskConfig<
  Outputs extends readonly [DcCurrentDensityOutput, ...DcCurrentDensityOutput[]] = readonly [
    DcCurrentDensityOutput,
    ...DcCurrentDensityOutput[],
  ],
> = Readonly<{
  parameters: Readonly<{
    relativeTolerance: FloatParameter<'float64', 'DimensionlessRatio'>
    maxIterations: number | NonFloatParameter<'int32', number>
  }>
  initializations: readonly [Extract<DcCurrentDensityInitialization, { methodId: 'dc.voxel-grid' }>]
  boundaryConditions:
    | readonly [
        Extract<DcCurrentDensityBoundaryCondition, { methodId: 'dc.source-potential' }>,
        Extract<DcCurrentDensityBoundaryCondition, { methodId: 'dc.reference-potential' }>,
      ]
    | readonly [
        Extract<DcCurrentDensityBoundaryCondition, { methodId: 'dc.reference-potential' }>,
        Extract<DcCurrentDensityBoundaryCondition, { methodId: 'dc.source-potential' }>,
      ]
  outputs: Outputs
}>

type DcCurrentDensityArtifactTypes<Outputs extends readonly DcCurrentDensityOutput[]> = Readonly<{
  [Output in Outputs[number] as Output['key']]: Output['methodId'] extends 'dc.current-density'
    ? 'caemble.dc/current-density@1'
    : Output['methodId'] extends 'dc.total-current'
      ? 'caemble.dc/total-current@1'
      : Output['methodId'] extends 'dc.joule-heating'
        ? 'caemble.dc/joule-heating@1'
        : never
}>

export declare function dcCurrentDensity<
  const Outputs extends readonly [DcCurrentDensityOutput, ...DcCurrentDensityOutput[]],
>(
  config: DcCurrentDensityTaskConfig<Outputs>,
): DefinedKernelTask<
  DcCurrentDensityTaskConfig<Outputs>,
  DcCurrentDensityArtifactTypes<Outputs>,
  Readonly<{
    iterations: number
    relativeResidual: number
  }>,
  Readonly<Record<never, never>>
>

export type SteadyStateHeatInitialization = Readonly<{
  methodId: 'heat.voxel-grid'
  target: readonly `structure.geometry.${string}`[]
  parameters: Readonly<{
    gridShape: NonFloatParameter<'int32', readonly [number, number, number]>
  }>
}>

export type SteadyStateHeatBoundaryCondition = Readonly<{
  methodId: 'heat.fixed-temperature'
  target: readonly `structure.surface.${string}`[]
  parameters: Readonly<{
    temperature: FloatParameter<'float64', 'thermodynamics.Temperature'>
  }>
}>

export type SteadyStateHeatOutput =
  | Readonly<{
      key: string
      methodId: 'heat.temperature'
      target: readonly `structure.geometry.${string}`[]
      parameters: Readonly<Record<string, never>>
    }>
  | Readonly<{
      key: string
      methodId: 'heat.maximum-temperature'
      target: readonly `structure.geometry.${string}`[]
      parameters: Readonly<Record<string, never>>
    }>

export type SteadyStateHeatThermalDomainMaterialVariables = Readonly<{
  'thermal.conductivity': MaterialDataValueDescriptor<'thermal.conductivity'>
}>

export type SteadyStateHeatTaskConfig<
  Outputs extends readonly [SteadyStateHeatOutput, ...SteadyStateHeatOutput[]] = readonly [
    SteadyStateHeatOutput,
    ...SteadyStateHeatOutput[],
  ],
> = Readonly<{
  parameters: Readonly<{
    relativeTolerance: FloatParameter<'float64', 'DimensionlessRatio'>
    maxIterations: number | NonFloatParameter<'int32', number>
  }>
  initializations: readonly [Extract<SteadyStateHeatInitialization, { methodId: 'heat.voxel-grid' }>]
  boundaryConditions: readonly SteadyStateHeatBoundaryCondition[]
  outputs: Outputs
}>

type SteadyStateHeatArtifactTypes<Outputs extends readonly SteadyStateHeatOutput[]> = Readonly<{
  [Output in Outputs[number] as Output['key']]: Output['methodId'] extends 'heat.temperature'
    ? 'caemble.heat/temperature@1'
    : Output['methodId'] extends 'heat.maximum-temperature'
      ? 'caemble.heat/maximum-temperature@1'
      : never
}>

export declare function steadyStateHeat<
  const Outputs extends readonly [SteadyStateHeatOutput, ...SteadyStateHeatOutput[]],
>(
  config: SteadyStateHeatTaskConfig<Outputs>,
): DefinedKernelTask<
  SteadyStateHeatTaskConfig<Outputs>,
  SteadyStateHeatArtifactTypes<Outputs>,
  Readonly<{
    iterations: number
    relativeResidual: number
  }>,
  Readonly<{
    heatSource: 'caemble.dc/joule-heating@1' | undefined
  }>
>
