// Generated by scripts/generate-cad-api.mjs. Do not edit.
export const CAEMBLE_CORE_DECLARATION_VERSION = '0.0.0' as const
export const CAEMBLE_KERNEL_DECLARATION_VERSION = '0.0.0' as const
export const CAEMBLE_MONACO_VERSION = '0.56.0' as const
export const CAEMBLE_TYPESCRIPT_VERSION = '5.9.3' as const
export const QUANTITY_KIND_DATA_VERSION = '0.0.0' as const
export const CAD_API_DECLARATION_FINGERPRINT =
  'e205a331c8e242d57673b9555aa94afa9f639a1922758afec11c2e853e10c372' as const
export const KERNEL_AUTHORING_VERSIONS = Object.freeze({
  'dc-current-density': '0.0.0',
  'steady-state-heat': '0.0.0',
})
