// Generated by scripts/generate-cad-api.mjs from data.ts. Do not edit.
import { quantityKindData } from './runtimeData'
import { QuantityKindEntry } from './runtime'
import type { QuantityKindDefinition, QuantityKindName } from './runtime'

export type {
  ApplicableUnit,
  CartesianBasis,
  QuantityKindComponentShape,
  QuantityKindComponentValue,
  QuantityKindDefinition,
  QuantityKindDomain,
  QuantityKindName,
  QuantityKindNameForDomain,
  QuantityKindTensorOrder,
  QuantityMetadata,
  QuantityValueReference,
  ScalarQuantityKindName,
  TensorQuantityKindName,
} from './runtime'

export { transformQuantityValue } from './runtime'
export { identityCartesianBasis } from './identityBasis'
export { quantityKindData } from './runtimeData'

export const QuantityKind = Object.freeze(
  Object.fromEntries(
    (Object.keys(quantityKindData) as QuantityKindName[]).map((name) => [name, new QuantityKindEntry(name)]),
  ),
) as unknown as { readonly [Name in QuantityKindName]: QuantityKindDefinition<Name> }
