# Generated by Django 4.2.4 on 2024-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_identificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationtoken',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
