# Generated by Django 4.2.4 on 2024-09-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_identificationtoken_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationtoken',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
