// @caemble/core/v2 declaration version: 2.1.0
export {
  Mat,
  Material,
} from '../index'

export type {
  ArrayAttributes,
  BooleanAttributes,
  BoxAttributes,
  CartesianBasis,
  CylinderAttributes,
  CurvedEdgeCylinderAttributes,
  CurvedEdgeCylinderFourierMode,
  CurvedEdgeCylinderTaylorCurve,
  CurvedSurfaceSphereAttributes,
  CurvedSurfaceSphereFourierMode,
  DataAxis,
  DataDType,
  DataValueDescriptor,
  ExperimentParameter,
  ExperimentParameters,
  ExperimentRule,
  ExperimentTarget,
  FloatDataDType,
  FiberAttributes,
  FiberFourierMode,
  FiberHelix,
  Geometry,
  GeometryAttributes,
  MaterialDataValueDescriptor,
  MaterialVariables,
  MatrixValue,
  QuantityKindDomain,
  QuantityKindName,
  QuantityKindNameForDomain,
  RecordedDataResult,
  RecordedDataResultAxis,
  RecordedDataRule,
  Rotation,
  ShellAttributes,
  ScalarQuantityKindName,
  SolverParameters,
  StructureGroupMap,
  SphereAttributes,
  Tensor,
  TensorQuantityKindName,
  UcumUnit,
  Vec3,
  VarsSchemaEntry,
} from '../index'

import type {
  CartesianBasis,
  DataAxis,
  ExperimentParameters,
  ExperimentRule,
  ExperimentTarget,
  RecordedDataRule,
  RecordedDataResultAxis,
  SolverParameters,
  StructureGroupMap,
  Tensor,
  UcumUnit,
  VarsSchemaEntry,
} from '../index'

export type VarsSchemaDefinition = Readonly<Record<string, Readonly<VarsSchemaEntry>>>

type ShapeSource<Entry extends VarsSchemaEntry> = Entry['min'] extends readonly unknown[]
  ? Entry['min']
  : Entry['max']

type WidenTensor<Value> = Value extends number
  ? number
  : Value extends readonly unknown[]
    ? { readonly [Index in keyof Value]: WidenTensor<Value[Index]> }
    : never

export type InferVars<Schema extends VarsSchemaDefinition> = Readonly<{
  [Key in keyof Schema]: WidenTensor<ShapeSource<Schema[Key]>>
}>

export type ModelContext<Schema extends VarsSchemaDefinition> = Readonly<{
  vars: InferVars<Schema>
}>

export type StructureDefinitionOptions<Schema extends VarsSchemaDefinition> = Readonly<{
  geometry: (context: ModelContext<Schema>) => unknown
  lengthUnit: UcumUnit
  varsSchema: Schema
  geometryGroup?: StructureGroupMap
  surfaceGroup?: StructureGroupMap
}>

type Float64Parameter<QuantityKind extends string> = Readonly<{
  dtype: 'float64'
  value: number | readonly unknown[]
  unit: UcumUnit
  quantityKind: QuantityKind
  axes?: readonly DataAxis[]
  basis?: never
}>

export type MaterialFloat64Parameter<QuantityKind extends string> = Float64Parameter<QuantityKind> & Readonly<{
  errorRate: number
}>

type TensorFloat64Parameter<QuantityKind extends string> = Omit<Float64Parameter<QuantityKind>, 'basis'> & Readonly<{
  basis?: CartesianBasis
}>

type MaterialTensorFloat64Parameter<QuantityKind extends string> = TensorFloat64Parameter<QuantityKind> & Readonly<{
  errorRate: number
}>

type Int32Parameter<Value extends number | readonly unknown[] = number> = Readonly<{
  dtype: 'int32'
  value: Value
  axes?: readonly DataAxis[]
  unit?: never
  quantityKind?: never
  basis?: never
}>

type SolverRule<
  MethodId extends string,
  Target extends ExperimentTarget,
  Parameters extends ExperimentParameters,
> = Readonly<{
  target: readonly Target[]
  label: string
  methodId: MethodId
  parameters: Parameters
}>

export declare function structure<const Schema extends VarsSchemaDefinition>(
  options: StructureDefinitionOptions<Schema>,
): Readonly<{
  readonly apiVersion: 2
  readonly documentType: 'structure'
  readonly varsSchema: Schema
}>

// <generated:solver-authoring>
// Generated by scripts/generate-cad-api.mjs from registered SolverSpec values. Do not edit.
export type DcCurrentDensityInitializationsRule =
  | SolverRule<
    'dc.voxel-grid',
    `structure.geometry.${string}`,
    Readonly<{
        gridShape: Int32Parameter<readonly [number, number, number]>
      }>
  >

export type DcCurrentDensityBoundaryConditionsRule =
  | SolverRule<
    'dc.source-potential',
    `structure.surface.${string}`,
    Readonly<{
        voltage: Float64Parameter<'electromagnetism.Voltage'>
      }>
  >
  | SolverRule<
    'dc.reference-potential',
    `structure.surface.${string}`,
    Readonly<{
        voltage: Float64Parameter<'electromagnetism.Voltage'>
      }>
  >

export type DcCurrentDensityRecordedDataRule =
  | SolverRule<
    'dc.current-density',
    `structure.geometry.${string}`,
    Readonly<{
        crossSectionPosition: Float64Parameter<'DimensionlessRatio'>
      }>
  > & Readonly<{ result: Readonly<{
      dtype: 'float64'
      unit: UcumUnit
      quantityKind: 'electromagnetism.ElectricCurrentDensity'
      basis?: CartesianBasis
      axes: readonly [RecordedDataResultAxis, RecordedDataResultAxis]
    }> }>
  | SolverRule<
    'dc.total-current',
    `structure.geometry.${string}`,
    Readonly<{
        crossSectionPosition: Float64Parameter<'DimensionlessRatio'>
      }>
  > & Readonly<{ result: Readonly<{
      dtype: 'float64'
      unit: UcumUnit
      quantityKind: 'electromagnetism.ElectricCurrent'
      basis?: never
      axes?: readonly RecordedDataResultAxis[]
    }> }>

export type DcCurrentDensityConductorMaterialVariables = Readonly<{
    electricalConductivity: MaterialTensorFloat64Parameter<'electromagnetism.ElectricConductivity'>
  }>

export type DcCurrentDensityOptions<Schema extends VarsSchemaDefinition> = StructureDefinitionOptions<Schema> & Readonly<{
  solver: Readonly<{
    name: 'dc-current-density'
    version: '2.0.0'
    parameters: (context: ModelContext<Schema>) => Readonly<{
          relativeTolerance: Float64Parameter<'DimensionlessRatio'>
          maxIterations: number | Int32Parameter
        }>
  }>
  initializations?: (context: ModelContext<Schema>) => readonly DcCurrentDensityInitializationsRule[]
  boundaryConditions?: (context: ModelContext<Schema>) => readonly DcCurrentDensityBoundaryConditionsRule[]
  recordedData?: (context: ModelContext<Schema>) => readonly DcCurrentDensityRecordedDataRule[]
}>

export type RegisteredSolverName =
  | 'dc-current-density'

type RegisteredExperimentDefinitionOptions<
  Schema extends VarsSchemaDefinition,
  SolverName extends RegisteredSolverName,
> = SolverName extends 'dc-current-density'
  ? DcCurrentDensityOptions<Schema>
  : never

type GenericExperimentDefinitionOptions<
  Schema extends VarsSchemaDefinition,
  SolverName extends string,
> = StructureDefinitionOptions<Schema> & Readonly<{
  solver: Readonly<{
    name: SolverName
    version: string
    parameters: (context: ModelContext<Schema>) => SolverParameters
  }>
  initializations?: (context: ModelContext<Schema>) => readonly ExperimentRule[]
  boundaryConditions?: (context: ModelContext<Schema>) => readonly ExperimentRule[]
  recordedData?: (context: ModelContext<Schema>) => readonly RecordedDataRule[]
}>

export type ExperimentDefinitionOptions<
  Schema extends VarsSchemaDefinition,
  SolverName extends string = string,
> = SolverName extends RegisteredSolverName
  ? RegisteredExperimentDefinitionOptions<Schema, SolverName>
  : GenericExperimentDefinitionOptions<Schema, SolverName>

export declare function experiment<const Schema extends VarsSchemaDefinition>(
  options: DcCurrentDensityOptions<Schema>,
): Readonly<{
  readonly apiVersion: 2
  readonly documentType: 'experiment'
  readonly varsSchema: Schema
}>

export declare function experiment<
  const Schema extends VarsSchemaDefinition,
  const SolverName extends string,
>(options: GenericExperimentDefinitionOptions<Schema, SolverName> & Readonly<{
  solver: Readonly<{ name: SolverName extends RegisteredSolverName ? never : SolverName }>
}>): Readonly<{
  readonly apiVersion: 2
  readonly documentType: 'experiment'
  readonly varsSchema: Schema
}>
// </generated:solver-authoring>

export type ExternalVars = Readonly<Record<string, Tensor>>
