// Generated by scripts/generate-cad-api.mjs. Do not edit.
export const CAEMBLE_CORE_V2_DECLARATION_VERSION = '2.1.0' as const
export const CAEMBLE_MONACO_VERSION = '0.55.1' as const
export const CAEMBLE_TYPESCRIPT_VERSION = '5.9.3' as const
export const QUANTITY_KIND_DATA_VERSION = '1.0.0' as const
export const SOLVER_AUTHORING_VERSIONS = Object.freeze({
  "dc-current-density": "2.0.0"
})
