user ubuntu;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {
	server {
		listen 80;
		server_name qws.qutat.net;
		return 301 https://qws.qutat.net;
	}
	server {
		listen 443 ssl; # managed by Certbot	
	        ssl_certificate /etc/letsencrypt/live/qws.qutat.net/fullchain.pem; # managed by Certbot
	        ssl_certificate_key /etc/letsencrypt/live/qws.qutat.net/privkey.pem; # managed by Certbot
	        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
		location / {
			proxy_pass http://localhost:3000;
		}
	}

	upstream django {
		server unix:///home/ubuntu/bin/nginx_to_django.sock;
	} #uwsgi
	server {
		listen 8000 ssl;
	        ssl_certificate /etc/letsencrypt/live/qws.qutat.net/fullchain.pem; # managed by Certbot
	        ssl_certificate_key /etc/letsencrypt/live/qws.qutat.net/privkey.pem; # managed by Certbot
	        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
		server_name qws.qutat.net;
		charset	utf-8;		
		client_max_body_size 75M;
		location / {
			include /etc/nginx/uwsgi_params; #uwsgi
			uwsgi_pass django; #uwsgi
			#proxy_pass http://localhost:8001; #runserver
		}
	}
}
