import { access, readFile, readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const checkOnly = process.argv.includes('--check')
const changed = []

const elementManifestPath = path.join(root, 'src/cad/elements/manifest.json')
const authoringManifestPath = path.join(root, 'src/cad/api/authoring-manifest.json')
const elementManifest = JSON.parse(await readFile(elementManifestPath, 'utf8'))
const authoringManifest = JSON.parse(await readFile(authoringManifestPath, 'utf8'))

function tsString(value) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}

function pascalCase(value) {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join('')
}

function groupedImports(entries, moduleKey, exportKey) {
  const modules = new Map()
  entries.forEach((entry) => {
    const names = modules.get(entry[moduleKey]) ?? []
    if (!names.includes(entry[exportKey])) names.push(entry[exportKey])
    modules.set(entry[moduleKey], names)
  })
  return [...modules.entries()].map(([moduleName, names]) => (
    `import { ${names.join(', ')} } from ${tsString(moduleName)}`
  )).join('\n')
}

async function loadBundledModule(entryPoint) {
  const result = await build({
    bundle: true,
    entryPoints: [entryPoint],
    format: 'esm',
    logLevel: 'silent',
    platform: 'node',
    target: 'node20',
    define: { 'import.meta.env.MODE': '"test"' },
    write: false,
  })
  const source = Buffer.from(result.outputFiles[0].text).toString('base64')
  return import(`data:text/javascript;base64,${source}`)
}

async function emit(relativePath, content) {
  const outputPath = path.join(root, relativePath)
  let current = ''
  try {
    current = await readFile(outputPath, 'utf8')
  } catch {
    // New generated file.
  }
  if (current === content) return
  changed.push(relativePath)
  if (!checkOnly) await writeFile(outputPath, content, 'utf8')
}

async function validateElementManifest() {
  if (elementManifest.version !== 2 || !Array.isArray(elementManifest.elements)) {
    throw new Error('src/cad/elements/manifest.json must be a v2 element manifest.')
  }
  const tags = new Set()
  for (const element of elementManifest.elements) {
    if (tags.has(element.tag)) throw new Error(`Duplicate CAD element manifest tag: ${element.tag}`)
    tags.add(element.tag)
    const definitionPath = path.join(root, 'src/cad/elements', `${element.definitionModule}.ts`)
    const runtimePath = path.join(root, 'src/cad/elements', `${element.runtimeModule}.ts`)
    const [definition, runtime] = await Promise.all([
      readFile(definitionPath, 'utf8'),
      readFile(runtimePath, 'utf8'),
    ])
    if (!definition.includes(`export type ${element.attributes}`)) {
      throw new Error(`${element.definitionModule} does not export ${element.attributes}.`)
    }
    if (!definition.includes(`export const ${element.manifestExport}`) || !definition.includes(`tag: '${element.tag}'`)) {
      throw new Error(`${element.definitionModule} does not define ${element.manifestExport} for ${element.tag}.`)
    }
    if (!runtime.includes(`export const ${element.definitionExport}`)) {
      throw new Error(`${element.runtimeModule} does not export ${element.definitionExport}.`)
    }
  }
}

function generatedElementRegistry() {
  const elements = elementManifest.elements
  return `// Generated by scripts/generate-cad-api.mjs from manifest.json. Do not edit.\n${groupedImports(
    elements,
    'definitionModule',
    'manifestExport',
  )}\n${groupedImports(elements, 'runtimeModule', 'definitionExport')}\nimport type { CadElementDefinition } from '../evaluation/types'\n\nexport const cadElementCatalog = [\n${elements.map((element) => `  ${element.manifestExport},`).join('\n')}\n] as const\n\nexport const cadElementDefinitions = [\n${elements.map((element) => `  ${element.definitionExport},`).join('\n')}\n] as const satisfies readonly CadElementDefinition[]\n`
}

function generatedJsxDeclaration() {
  const attributes = [...new Set(elementManifest.elements.map((element) => element.attributes))].sort()
  return `// Generated by scripts/generate-cad-api.mjs from elements/manifest.json. Do not edit.\nimport type {\n${attributes.map((name) => `  ${name},`).join('\n')}\n} from '@caemble/core/v2'\n\ndeclare global {\n  function h(type: unknown, attributes: unknown, ...children: unknown[]): unknown\n  function Fragment(props: { children?: unknown }): unknown\n\n  namespace JSX {\n    interface IntrinsicElements {\n${elementManifest.elements.map((element) => `      ${element.tag}: ${element.attributes}`).join('\n')}\n    }\n  }\n}\n\nexport {}\n`
}

function tensorValueType(axes) {
  if (!axes?.length) return 'number'
  return axes.reduceRight((value, axis) => {
    if (!Number.isSafeInteger(axis.length) || axis.length < 1 || axis.length > 64) {
      throw new Error('Generated authoring tuple axes must have a length from 1 through 64.')
    }
    return `readonly [${Array.from({ length: axis.length }, () => value).join(', ')}]`
  }, 'number')
}

function parameterType(parameter, material = false) {
  const value = parameter.value
  if (value.dtype === 'float64' && typeof value.quantityKind === 'string') {
    const parameterName = value.referenceBasis
      ? material ? 'MaterialTensorFloat64Parameter' : 'TensorFloat64Parameter'
      : material ? 'MaterialFloat64Parameter' : 'Float64Parameter'
    return `${parameterName}<${tsString(value.quantityKind)}>`
  }
  if (value.dtype === 'int32') {
    return value.axes?.length
      ? `Int32Parameter<${tensorValueType(value.axes)}>`
      : 'number | Int32Parameter'
  }
  throw new Error(`Unsupported generated Solver authoring parameter dtype: ${value.dtype}`)
}

function parameterRecord(parameters, material = false) {
  const entries = Object.entries(parameters)
  if (entries.length === 0) return 'Readonly<Record<string, never>>'
  return `Readonly<{\n${entries.map(([name, parameter]) => (
    `    ${name}${parameter.required === false ? '?' : ''}: ${parameterType(parameter, material)}`
  )).join('\n')}\n  }>`
}

function resultType(result) {
  if (result.dtype !== 'float64' || typeof result.quantityKind !== 'string') {
    throw new Error(`Unsupported generated Solver result dtype: ${result.dtype}`)
  }
  const axes = result.axes?.length
    ? `axes: readonly [${result.axes.map(() => 'RecordedDataResultAxis').join(', ')}]`
    : 'axes?: readonly RecordedDataResultAxis[]'
  return `Readonly<{\n    dtype: 'float64'\n    unit: UcumUnit\n    quantityKind: ${tsString(result.quantityKind)}\n    basis?: ${result.referenceBasis ? 'CartesianBasis' : 'never'}\n    ${axes}\n  }>`
}

function solverAuthoring(specs) {
  const sections = []
  specs.forEach((spec) => {
    const prefix = pascalCase(spec.name)
    Object.entries(spec.methods).forEach(([category, methods]) => {
      const ruleType = `${prefix}${pascalCase(category)}Rule`
      const variants = methods.map((method) => {
        const base = `SolverRule<\n    ${tsString(method.methodId)},\n    \`${method.target.source}.${method.target.kind}.\${string}\`,\n    ${parameterRecord(method.parameters).replaceAll('\n', '\n    ')}\n  >`
        return category === 'recordedData'
          ? `${base} & Readonly<{ result: ${resultType(method.result).replaceAll('\n', '\n  ')} }>`
          : base
      })
      sections.push(`export type ${ruleType} =${variants.length === 0
        ? ' never'
        : `\n${variants.map((variant) => `  | ${variant}`).join('\n')}`}`)
    })
    spec.materials.forEach((material) => {
      sections.push(`export type ${prefix}${pascalCase(material.role)}MaterialVariables = ${parameterRecord(
        material.parameters,
        true,
      )}`)
    })
    const solverParameters = parameterRecord(spec.parameters).replaceAll('\n', '\n      ')
    sections.push(`export type ${prefix}Options<Schema extends VarsSchemaDefinition> = StructureDefinitionOptions<Schema> & Readonly<{\n  solver: Readonly<{\n    name: ${tsString(spec.name)}\n    version: ${tsString(spec.version)}\n    parameters: (context: ModelContext<Schema>) => ${solverParameters}\n  }>\n  initializations?: (context: ModelContext<Schema>) => readonly ${prefix}InitializationsRule[]\n  boundaryConditions?: (context: ModelContext<Schema>) => readonly ${prefix}BoundaryConditionsRule[]\n  recordedData?: (context: ModelContext<Schema>) => readonly ${prefix}RecordedDataRule[]\n}>`)
  })

  const registeredNames = specs.map((spec) => tsString(spec.name))
  const registeredOptions = specs.map((spec, index) => (
    `${index === 0 ? '' : '  : '}SolverName extends ${tsString(spec.name)}\n  ? ${pascalCase(spec.name)}Options<Schema>`
  )).join('\n')
  const overloads = specs.map((spec) => `export declare function experiment<const Schema extends VarsSchemaDefinition>(\n  options: ${pascalCase(spec.name)}Options<Schema>,\n): Readonly<{\n  readonly apiVersion: 2\n  readonly documentType: 'experiment'\n  readonly varsSchema: Schema\n}>`).join('\n\n')

  return `// <generated:solver-authoring>\n// Generated by scripts/generate-cad-api.mjs from registered SolverSpec values. Do not edit.\n${sections.join('\n\n')}\n\nexport type RegisteredSolverName =\n${registeredNames.map((name) => `  | ${name}`).join('\n')}\n\ntype RegisteredExperimentDefinitionOptions<\n  Schema extends VarsSchemaDefinition,\n  SolverName extends RegisteredSolverName,\n> = ${registeredOptions}\n  : never\n\ntype GenericExperimentDefinitionOptions<\n  Schema extends VarsSchemaDefinition,\n  SolverName extends string,\n> = StructureDefinitionOptions<Schema> & Readonly<{\n  solver: Readonly<{\n    name: SolverName\n    version: string\n    parameters: (context: ModelContext<Schema>) => SolverParameters\n  }>\n  initializations?: (context: ModelContext<Schema>) => readonly ExperimentRule[]\n  boundaryConditions?: (context: ModelContext<Schema>) => readonly ExperimentRule[]\n  recordedData?: (context: ModelContext<Schema>) => readonly RecordedDataRule[]\n}>\n\nexport type ExperimentDefinitionOptions<\n  Schema extends VarsSchemaDefinition,\n  SolverName extends string = string,\n> = SolverName extends RegisteredSolverName\n  ? RegisteredExperimentDefinitionOptions<Schema, SolverName>\n  : GenericExperimentDefinitionOptions<Schema, SolverName>\n\n${overloads}\n\nexport declare function experiment<\n  const Schema extends VarsSchemaDefinition,\n  const SolverName extends string,\n>(options: GenericExperimentDefinitionOptions<Schema, SolverName> & Readonly<{\n  solver: Readonly<{ name: SolverName extends RegisteredSolverName ? never : SolverName }>\n}>): Readonly<{\n  readonly apiVersion: 2\n  readonly documentType: 'experiment'\n  readonly varsSchema: Schema\n}>\n// </generated:solver-authoring>`
}

function quantityKindTypes(quantityKindData) {
  const names = Object.keys(quantityKindData)
  const tensorNames = names.filter((name) => quantityKindData[name].tensorOrder > 0)
  return `// <generated:quantity-kind-types>\nexport type QuantityKindName =\n${names.map((name) => `  | ${tsString(name)}`).join('\n')}\nexport type TensorQuantityKindName =\n${tensorNames.map((name) => `  | ${tsString(name)}`).join('\n')}\nexport type ScalarQuantityKindName = Exclude<QuantityKindName, TensorQuantityKindName>\n// </generated:quantity-kind-types>`
}

function quantityKindFacade() {
  return `// Generated by scripts/generate-cad-api.mjs from data.ts. Do not edit.\nimport { quantityKindData } from './data'\nimport { QuantityKindEntry } from './runtime'\nimport type { QuantityKindDefinition, QuantityKindName } from './runtime'\n\nexport type {\n  ApplicableUnit,\n  CartesianBasis,\n  QuantityKindComponentShape,\n  QuantityKindComponentValue,\n  QuantityKindDefinition,\n  QuantityKindName,\n  QuantityKindTensorOrder,\n  QuantityMetadata,\n  ScalarQuantityKindName,\n  TensorQuantityKindName,\n} from './runtime'\n\nexport const QuantityKind = Object.freeze(Object.fromEntries(\n  (Object.keys(quantityKindData) as QuantityKindName[]).map((name) => [name, new QuantityKindEntry(name)]),\n)) as { readonly [Name in QuantityKindName]: QuantityKindDefinition<Name> }\n`
    .replace("from './data'", "from './runtimeData'")
    .replace(
      ')) as { readonly [Name in QuantityKindName]: QuantityKindDefinition<Name> }',
      ')) as unknown as { readonly [Name in QuantityKindName]: QuantityKindDefinition<Name> }',
    )
}

await validateElementManifest()

const [modelV2Runtime, coreRuntime] = await Promise.all([
  loadBundledModule(path.join(root, 'src/cad/model/v2.ts')),
  loadBundledModule(path.join(root, 'src/cad/model/core.ts')),
])
if (
  typeof modelV2Runtime.structure !== 'function'
  || typeof modelV2Runtime.experiment !== 'function'
  || typeof modelV2Runtime.StructureDefinitionV2 !== 'function'
  || typeof modelV2Runtime.ExperimentDefinitionV2 !== 'function'
  || typeof coreRuntime.Material !== 'function'
  || typeof coreRuntime.Mat !== 'function'
) {
  throw new Error('@caemble/core/v2 runtime exports do not match the declaration generator contract.')
}

const modulesDirectory = path.join(root, 'src/solver/modules')
const solverDirectories = (await readdir(modulesDirectory, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort()
const specs = []
for (const directory of solverDirectories) {
  const specPath = path.join(modulesDirectory, directory, 'spec.ts')
  try {
    await access(specPath)
  } catch {
    continue
  }
  const module = await loadBundledModule(specPath)
  const spec = Object.values(module).find((value) => (
    value && typeof value === 'object' && 'name' in value && 'version' in value && 'methods' in value
  ))
  if (!spec) throw new Error(`No SolverSpec export was found in ${specPath}.`)
  specs.push(spec)
}
if (specs.length === 0) throw new Error('At least one registered SolverSpec is required for authoring generation.')

const quantityModule = await loadBundledModule(path.join(root, 'src/quantitykind/data.ts'))
const quantityKindData = quantityModule.quantityKindData
if (!quantityKindData) throw new Error('quantityKindData could not be loaded for declaration generation.')
if (!/^[a-z0-9._-]+$/i.test(authoringManifest.quantityKindDataVersion)) {
  throw new Error('quantityKindDataVersion must be safe to use in an asset filename.')
}
await emit(
  `public/assets/quantity-kind-data-${authoringManifest.quantityKindDataVersion}.js`,
  `// Generated by scripts/generate-cad-api.mjs from src/quantitykind/data.ts. Do not edit.\nconst data=${JSON.stringify(quantityKindData)}\nfor(const entry of Object.values(data)){Object.freeze(entry.applicableUnits);Object.freeze(entry)}\nexport const quantityKindData=Object.freeze(data)\n`,
)

const v2DeclarationPath = path.join(root, 'src/cad/api/caemble-core-v2.d.ts')
const v2Declaration = await readFile(v2DeclarationPath, 'utf8')
  .then((source) => source
    .replace(
      /^\/\/ @caemble\/core\/v2 declaration version: .*$/m,
      `// @caemble/core/v2 declaration version: ${authoringManifest.coreV2DeclarationVersion}`,
    )
    .replace(
      /\/\/ <generated:solver-authoring>[\s\S]*?\/\/ <\/generated:solver-authoring>/,
      solverAuthoring(specs),
    ))

const coreDeclarationPath = path.join(root, 'src/cad/api/caemble-core.d.ts')
const coreDeclaration = await readFile(coreDeclarationPath, 'utf8')
  .then((source) => source.replace(
    /\/\/ <generated:quantity-kind-types>[\s\S]*?\/\/ <\/generated:quantity-kind-types>/,
    quantityKindTypes(quantityKindData),
  ))

const packageJson = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'))
if (packageJson.dependencies['monaco-editor'] !== authoringManifest.monacoVersion) {
  throw new Error('authoring-manifest Monaco version must equal the exact package.json dependency.')
}
if (packageJson.devDependencies.typescript !== authoringManifest.typescriptVersion) {
  throw new Error('authoring-manifest TypeScript version must equal the exact package.json devDependency.')
}
const monacoTypeScriptMetadata = await readFile(
  path.join(root, 'node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServicesMetadata.js'),
  'utf8',
)
const monacoTypeScriptVersion = monacoTypeScriptMetadata.match(/typescriptVersion = "([^"]+)"/)?.[1]
if (monacoTypeScriptVersion !== authoringManifest.typescriptVersion) {
  throw new Error('The test TypeScript version must match the TypeScript version embedded in Monaco.')
}
const solverVersions = JSON.stringify(Object.fromEntries(
  specs.map((spec) => [spec.name, spec.version]),
), null, 2)
const generatedVersions = `// Generated by scripts/generate-cad-api.mjs. Do not edit.
export const CAEMBLE_CORE_V2_DECLARATION_VERSION = ${tsString(authoringManifest.coreV2DeclarationVersion)} as const
export const CAEMBLE_MONACO_VERSION = ${tsString(authoringManifest.monacoVersion)} as const
export const CAEMBLE_TYPESCRIPT_VERSION = ${tsString(authoringManifest.typescriptVersion)} as const
export const QUANTITY_KIND_DATA_VERSION = ${tsString(authoringManifest.quantityKindDataVersion)} as const
export const SOLVER_AUTHORING_VERSIONS = Object.freeze(${solverVersions})
`

await Promise.all([
  emit('src/cad/elements/generated.ts', generatedElementRegistry()),
  emit('src/cad/api/cad-jsx.d.ts', generatedJsxDeclaration()),
  emit('src/cad/api/caemble-core-v2.d.ts', v2Declaration),
  emit('src/cad/api/caemble-core.d.ts', coreDeclaration),
  emit('src/quantitykind/index.ts', quantityKindFacade()),
  emit('src/cad/api/generatedVersions.ts', generatedVersions),
])

if (checkOnly && changed.length > 0) {
  console.error(`Generated CAD API files are stale:\n${changed.map((file) => `- ${file}`).join('\n')}`)
  process.exitCode = 1
} else if (!checkOnly && changed.length > 0) {
  console.log(`Updated generated CAD API files:\n${changed.map((file) => `- ${file}`).join('\n')}`)
}
