[FDTD:Waveform]
#EXE_WIN=solvers\waveform\_exe_win.bat
WIN_ARG_0=./.venv/Scripts/python.exe
WIN_ARG_1=./.solvers/waveform/script.py
#WIN_ARG_0=solvers\script.dist\script.exe

LINUX_ARG_0=./.venv/Scripts/python
LINUX_ARG_1=./.solvers/waveform/script.py
INPUT_VARIABLES=./.solvers/waveform/_input_variables/
IS_DEFAULT=1

[FDTD:MEEP]
#EXE_WIN=solvers\meep\_exe_win.bat
WIN_ARG_0=wsl bash
WIN_ARG_1=./.solvers/meep/execute_at_conda.sh
LINUX_ARG_0=wsl bash
LINUX_ARG_1=./.solvers/meep/execute_at_conda.sh
INPUT_VARIABLES=./.solvers/meep/_input_variables/


